#!/usr/bin/env -S node
import type { Contract as Start } from '../../snapshots/1e8412e162dbbe69f4bb3bf8d07f0280ae67eaab15c34dcf201e67468315428d/contract';
import startContract from '../../snapshots/1e8412e162dbbe69f4bb3bf8d07f0280ae67eaab15c34dcf201e67468315428d/contract.json' with { type: 'json' };
import type { Contract as End } from '../../snapshots/989e28ef6d0105e7d8e736984f907fd95d35f0cd771276322ec0ab6e51400117/contract';
import endContract from '../../snapshots/989e28ef6d0105e7d8e736984f907fd95d35f0cd771276322ec0ab6e51400117/contract.json' with { type: 'json' };
import {
  Migration,
  MigrationCLI,
  checkExpression,
  col,
  fn,
  lit,
  primaryKey,
} from '@prisma/orm-postgres/migration';

export default class M extends Migration<Start, End> {
  override readonly startContractJson = startContract;
  override readonly endContractJson = endContract;

  override get operations() {
    return [
      this.dropTable({ schema: 'public', table: 'post' }),
      this.dropTable({ schema: 'public', table: 'user' }),
      this.createTable({
        schema: 'public',
        table: 'competition',
        columns: [
          col('code', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('country', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('logoUrl', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('name', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('shortName', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('type', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'competition_type_check_494aa115',
            "\"type\" IN ('league', 'cup', 'super_cup', 'continental', 'friendly', 'other')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'data_source',
        columns: [
          col('baseUrl', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('code', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('isEnabled', 'bool', {
            notNull: true,
            default: lit(true),
            codecRef: { codecId: 'pg/bool@1' },
          }),
          col('isOfficial', 'bool', {
            notNull: true,
            default: lit(false),
            codecRef: { codecId: 'pg/bool@1' },
          }),
          col('licenseNotes', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('name', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'favourite_player',
        columns: [
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('pinnedAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('playerId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('sortOrder', 'int4', {
            notNull: true,
            default: lit(0),
            codecRef: { codecId: 'pg/int4@1' },
          }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'football_match',
        columns: [
          col('attendance', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('awayExtraTimeScore', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('awayPenaltyScore', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('awayScore', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('awayTeamId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('competitionId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('homeExtraTimeScore', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('homePenaltyScore', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('homeScore', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('homeTeamId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('kickoff', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('leg', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('matchday', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('neutralVenue', 'bool', {
            notNull: true,
            default: lit(false),
            codecRef: { codecId: 'pg/bool@1' },
          }),
          col('round', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('seasonId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('stage', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('status', 'text', {
            notNull: true,
            default: lit('scheduled'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('venue', 'text', { codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'football_match_status_check_ab2c413f',
            "\"status\" IN ('scheduled', 'postponed', 'cancelled', 'live', 'halftime', 'extra_time', 'penalties', 'finished', 'abandoned')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'kit_theme',
        columns: [
          col('accentColor', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('assets', 'json', { codecRef: { codecId: 'pg/json@1' } }),
          col('backgroundColor', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('effects', 'json', { codecRef: { codecId: 'pg/json@1' } }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('name', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('palette', 'json', { codecRef: { codecId: 'pg/json@1' } }),
          col('primaryColor', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('seasonId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('secondaryColor', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('surfaceColor', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('textColor', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('textureUrl', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('type', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'kit_theme_type_check_ebae989d',
            "\"type\" IN ('home', 'away', 'third', 'goalkeeper', 'special')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'lineup',
        columns: [
          col('coachName', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('formation', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('isConfirmed', 'bool', {
            notNull: true,
            default: lit(false),
            codecRef: { codecId: 'pg/bool@1' },
          }),
          col('matchId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('teamId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'lineup_player',
        columns: [
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('enteredMinute', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('leftMinute', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('lineupId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('playerId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('position', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('positionX', 'float8', { codecRef: { codecId: 'pg/float8@1' } }),
          col('positionY', 'float8', { codecRef: { codecId: 'pg/float8@1' } }),
          col('role', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('shirtNumber', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'lineup_player_role_check_bf543ada',
            "\"role\" IN ('starter', 'substitute')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'manual_override',
        columns: [
          col('confidence', 'text', {
            notNull: true,
            default: lit('manual_verified'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('entityId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('entityType', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('fieldName', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('payload', 'json', { notNull: true, codecRef: { codecId: 'pg/json@1' } }),
          col('reason', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('sourceUrl', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'manual_override_confidence_check_5fe79b9e',
            "\"confidence\" IN ('exact_provider', 'derived', 'manual_verified', 'reconstructed', 'approximate', 'unknown')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'match_diary_entry',
        columns: [
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('favouriteGoalEventId', 'uuid', { codecRef: { codecId: 'pg/uuid@1' } }),
          col('favouritePlayerId', 'uuid', { codecRef: { codecId: 'pg/uuid@1' } }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('matchId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('notes', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('rating', 'float8', { codecRef: { codecId: 'pg/float8@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('watchType', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('watched', 'bool', {
            notNull: true,
            default: lit(true),
            codecRef: { codecId: 'pg/bool@1' },
          }),
          col('watchedAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-temporal@1' } }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'match_diary_entry_watchType_check_0ac427c3',
            "\"watchType\" IN ('live', 'replay', 'highlights_only')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'match_event',
        columns: [
          col('bodyPart', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('confidence', 'text', {
            notNull: true,
            default: lit('unknown'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('coordinateSystem', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('dataSourceId', 'uuid', { codecRef: { codecId: 'pg/uuid@1' } }),
          col('endX', 'float8', { codecRef: { codecId: 'pg/float8@1' } }),
          col('endY', 'float8', { codecRef: { codecId: 'pg/float8@1' } }),
          col('eventOrder', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('matchId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('minute', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('outcome', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('period', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('playPattern', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('primaryPlayerId', 'uuid', { codecRef: { codecId: 'pg/uuid@1' } }),
          col('rawData', 'json', { codecRef: { codecId: 'pg/json@1' } }),
          col('relatedPlayerId', 'uuid', { codecRef: { codecId: 'pg/uuid@1' } }),
          col('second', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('sequenceId', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('startX', 'float8', { codecRef: { codecId: 'pg/float8@1' } }),
          col('startY', 'float8', { codecRef: { codecId: 'pg/float8@1' } }),
          col('teamId', 'uuid', { codecRef: { codecId: 'pg/uuid@1' } }),
          col('type', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('xG', 'float8', { codecRef: { codecId: 'pg/float8@1' } }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'match_event_confidence_check_5fe79b9e',
            "\"confidence\" IN ('exact_provider', 'derived', 'manual_verified', 'reconstructed', 'approximate', 'unknown')",
          ),
          checkExpression(
            'match_event_type_check_998a6540',
            "\"type\" IN ('period_start', 'period_end', 'kickoff', 'goal', 'own_goal', 'penalty_goal', 'missed_penalty', 'shot', 'pass', 'carry', 'assist', 'yellow_card', 'red_card', 'substitution', 'injury', 'offside', 'foul', 'save', 'other')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'match_statistic',
        columns: [
          col('clearances', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('completedPasses', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('corners', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('dataSourceId', 'uuid', { codecRef: { codecId: 'pg/uuid@1' } }),
          col('fouls', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('interceptions', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('matchId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('offsides', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('passAccuracy', 'float8', { codecRef: { codecId: 'pg/float8@1' } }),
          col('passes', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('possession', 'float8', { codecRef: { codecId: 'pg/float8@1' } }),
          col('rawData', 'json', { codecRef: { codecId: 'pg/json@1' } }),
          col('redCards', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('shots', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('shotsOnTarget', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('tackles', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('teamId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('xG', 'float8', { codecRef: { codecId: 'pg/float8@1' } }),
          col('yellowCards', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'media_item',
        columns: [
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('dataSourceId', 'uuid', { codecRef: { codecId: 'pg/uuid@1' } }),
          col('description', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('externalMediaId', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('isOfficial', 'bool', {
            notNull: true,
            default: lit(false),
            codecRef: { codecId: 'pg/bool@1' },
          }),
          col('matchId', 'uuid', { codecRef: { codecId: 'pg/uuid@1' } }),
          col('playerId', 'uuid', { codecRef: { codecId: 'pg/uuid@1' } }),
          col('publishedAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-temporal@1' } }),
          col('seasonId', 'uuid', { codecRef: { codecId: 'pg/uuid@1' } }),
          col('thumbnailUrl', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('title', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('type', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('url', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'media_item_type_check_0b2bf1f8',
            "\"type\" IN ('match_highlight', 'goal_clip', 'interview', 'press_conference', 'training', 'historical', 'other')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'model_version',
        columns: [
          col('algorithm', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('metrics', 'json', { codecRef: { codecId: 'pg/json@1' } }),
          col('name', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('notes', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('trainedAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-temporal@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('version', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'player',
        columns: [
          col('birthDate', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-temporal@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('displayName', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('firstName', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('isActive', 'bool', {
            notNull: true,
            default: lit(true),
            codecRef: { codecId: 'pg/bool@1' },
          }),
          col('lastName', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('nationality', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('portraitUrl', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('preferredFoot', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('primaryPosition', 'text', {
            notNull: true,
            default: lit('unknown'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'player_primaryPosition_check_ae28b165',
            "\"primaryPosition\" IN ('goalkeeper', 'defender', 'midfielder', 'forward', 'unknown')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'player_absence',
        columns: [
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('dataSourceId', 'uuid', { codecRef: { codecId: 'pg/uuid@1' } }),
          col('endDate', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-temporal@1' } }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('notes', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('playerId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('reason', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('seasonId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('startDate', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-temporal@1' } }),
          col('status', 'text', {
            notNull: true,
            default: lit('unknown'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('type', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'player_absence_status_check_e00853a1',
            "\"status\" IN ('active', 'recovered', 'unknown')",
          ),
          checkExpression(
            'player_absence_type_check_85b3790c',
            "\"type\" IN ('injury', 'suspension', 'illness', 'rest', 'other')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'player_match_statistic',
        columns: [
          col('assists', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('carries', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('completedPasses', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('dataSourceId', 'uuid', { codecRef: { codecId: 'pg/uuid@1' } }),
          col('duelsTotal', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('duelsWon', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('goals', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('interceptions', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('keyPasses', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('matchId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('minutes', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('passAccuracy', 'float8', { codecRef: { codecId: 'pg/float8@1' } }),
          col('passes', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('playerId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('progressiveCarries', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('progressivePasses', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('rating', 'float8', { codecRef: { codecId: 'pg/float8@1' } }),
          col('rawData', 'json', { codecRef: { codecId: 'pg/json@1' } }),
          col('recoveries', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('redCards', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('shots', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('shotsOnTarget', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('tackles', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('teamId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('touches', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('xA', 'float8', { codecRef: { codecId: 'pg/float8@1' } }),
          col('xG', 'float8', { codecRef: { codecId: 'pg/float8@1' } }),
          col('yellowCards', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'prediction',
        columns: [
          col('analysisSnapshot', 'json', { codecRef: { codecId: 'pg/json@1' } }),
          col('barcaWinProbability', 'float8', {
            notNull: true,
            codecRef: { codecId: 'pg/float8@1' },
          }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('drawProbability', 'float8', { notNull: true, codecRef: { codecId: 'pg/float8@1' } }),
          col('featureSnapshot', 'json', { codecRef: { codecId: 'pg/json@1' } }),
          col('generatedAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('isFinalPreKickoff', 'bool', {
            notNull: true,
            default: lit(false),
            codecRef: { codecId: 'pg/bool@1' },
          }),
          col('lockedAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-temporal@1' } }),
          col('matchId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('modelVersionId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('opponentWinProbability', 'float8', {
            notNull: true,
            codecRef: { codecId: 'pg/float8@1' },
          }),
          col('scoreDistribution', 'json', { codecRef: { codecId: 'pg/json@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'provider_mapping',
        columns: [
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('dataSourceId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('entityType', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('internalId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('metadata', 'json', { codecRef: { codecId: 'pg/json@1' } }),
          col('providerId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'provider_mapping_entityType_check_e5764765',
            "\"entityType\" IN ('season', 'competition', 'team', 'player', 'match', 'event', 'media', 'trophy')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'season',
        columns: [
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('endDate', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-temporal@1' } }),
          col('endYear', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('era', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('isCurrent', 'bool', {
            notNull: true,
            default: lit(false),
            codecRef: { codecId: 'pg/bool@1' },
          }),
          col('label', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('startDate', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-temporal@1' } }),
          col('startYear', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('visualKey', 'text', { codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'season_era_check_c445f71d',
            "\"era\" IN ('modern', 'older', 'historic')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'season_moment',
        columns: [
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('dataSourceId', 'uuid', { codecRef: { codecId: 'pg/uuid@1' } }),
          col('description', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('imageUrl', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('importance', 'int4', {
            notNull: true,
            default: lit(1),
            codecRef: { codecId: 'pg/int4@1' },
          }),
          col('matchId', 'uuid', { codecRef: { codecId: 'pg/uuid@1' } }),
          col('metadata', 'json', { codecRef: { codecId: 'pg/json@1' } }),
          col('occurredAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('playerId', 'uuid', { codecRef: { codecId: 'pg/uuid@1' } }),
          col('seasonId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('title', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('type', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'season_moment_type_check_1f727ceb',
            "\"type\" IN ('match', 'trophy', 'injury', 'debut', 'transfer', 'record', 'key_moment', 'historical', 'personal', 'other')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'squad_membership',
        columns: [
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('isCaptain', 'bool', {
            notNull: true,
            default: lit(false),
            codecRef: { codecId: 'pg/bool@1' },
          }),
          col('joinedAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-temporal@1' } }),
          col('leftAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-temporal@1' } }),
          col('playerId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('position', 'text', {
            notNull: true,
            default: lit('unknown'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('seasonId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('shirtNumber', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('teamId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'squad_membership_position_check_18b19a52',
            "\"position\" IN ('goalkeeper', 'defender', 'midfielder', 'forward', 'unknown')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'standing_snapshot',
        columns: [
          col('competitionId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('drawn', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('goalDifference', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('goalsAgainst', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('goalsFor', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('lost', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('matchday', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('played', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('points', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('position', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('seasonId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('snapshotAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-temporal@1' } }),
          col('teamId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('won', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'team',
        columns: [
          col('code', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('country', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('crestUrl', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('isBarcelona', 'bool', {
            notNull: true,
            default: lit(false),
            codecRef: { codecId: 'pg/bool@1' },
          }),
          col('name', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('shortName', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'trophy',
        columns: [
          col('category', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('imageUrl', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('modelUrl', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('name', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('shortName', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'trophy_win',
        columns: [
          col('competitionId', 'uuid', { codecRef: { codecId: 'pg/uuid@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('notes', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('seasonId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('trophyId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-temporal@1' },
          }),
          col('wonAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-temporal@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.addUnique({
        schema: 'public',
        table: 'competition',
        constraint: 'competition_code_key',
        columns: ['code'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'data_source',
        constraint: 'data_source_code_key',
        columns: ['code'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'favourite_player',
        constraint: 'favourite_player_playerId_key',
        columns: ['playerId'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'kit_theme',
        constraint: 'kit_theme_seasonId_type_key',
        columns: ['seasonId', 'type'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'lineup',
        constraint: 'lineup_matchId_teamId_key',
        columns: ['matchId', 'teamId'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'lineup_player',
        constraint: 'lineup_player_lineupId_playerId_key',
        columns: ['lineupId', 'playerId'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'match_diary_entry',
        constraint: 'match_diary_entry_matchId_key',
        columns: ['matchId'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'match_statistic',
        constraint: 'match_statistic_matchId_teamId_key',
        columns: ['matchId', 'teamId'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'model_version',
        constraint: 'model_version_version_key',
        columns: ['version'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'player_match_statistic',
        constraint: 'player_match_statistic_matchId_playerId_key',
        columns: ['matchId', 'playerId'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'provider_mapping',
        constraint: 'provider_mapping_dataSourceId_entityType_providerId_key',
        columns: ['dataSourceId', 'entityType', 'providerId'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'provider_mapping',
        constraint: 'provider_mapping_dataSourceId_entityType_internalId_key',
        columns: ['dataSourceId', 'entityType', 'internalId'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'season',
        constraint: 'season_label_key',
        columns: ['label'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'squad_membership',
        constraint: 'squad_membership_seasonId_teamId_playerId_key',
        columns: ['seasonId', 'teamId', 'playerId'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'standing_snapshot',
        constraint: 'standing_snapshot_seasonId_competitionId_matchday_teamId_key',
        columns: ['seasonId', 'competitionId', 'matchday', 'teamId'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'team',
        constraint: 'team_code_key',
        columns: ['code'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'football_match',
        index: 'football_match_awayTeamId_idx_17f82264',
        columns: ['awayTeamId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'football_match',
        index: 'football_match_competitionId_idx_53fccd3b',
        columns: ['competitionId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'football_match',
        index: 'football_match_homeTeamId_idx_2a4bf710',
        columns: ['homeTeamId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'football_match',
        index: 'football_match_kickoff_idx_59b357dd',
        columns: ['kickoff'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'football_match',
        index: 'football_match_seasonId_competitionId_idx_6016c8c0',
        columns: ['seasonId', 'competitionId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'football_match',
        index: 'football_match_seasonId_idx_aa50cbae',
        columns: ['seasonId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'football_match',
        index: 'football_match_status_kickoff_idx_8ddb02c2',
        columns: ['status', 'kickoff'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'kit_theme',
        index: 'kit_theme_seasonId_idx_aa50cbae',
        columns: ['seasonId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'lineup',
        index: 'lineup_matchId_idx_4caf5ecc',
        columns: ['matchId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'lineup',
        index: 'lineup_teamId_idx_f2b72ab3',
        columns: ['teamId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'lineup_player',
        index: 'lineup_player_lineupId_idx_ecd6b267',
        columns: ['lineupId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'lineup_player',
        index: 'lineup_player_playerId_idx_710cf1aa',
        columns: ['playerId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'manual_override',
        index: 'manual_override_entityType_entityId_idx_ea0fa809',
        columns: ['entityType', 'entityId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'match_diary_entry',
        index: 'match_diary_entry_favouriteGoalEventId_idx_d2f5cff7',
        columns: ['favouriteGoalEventId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'match_diary_entry',
        index: 'match_diary_entry_favouritePlayerId_idx_67a9e28a',
        columns: ['favouritePlayerId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'match_diary_entry',
        index: 'match_diary_entry_watchedAt_idx_89256024',
        columns: ['watchedAt'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'match_event',
        index: 'match_event_dataSourceId_idx_536a4d74',
        columns: ['dataSourceId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'match_event',
        index: 'match_event_matchId_eventOrder_idx_adf3d82c',
        columns: ['matchId', 'eventOrder'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'match_event',
        index: 'match_event_matchId_idx_4caf5ecc',
        columns: ['matchId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'match_event',
        index: 'match_event_matchId_type_idx_2c77437c',
        columns: ['matchId', 'type'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'match_event',
        index: 'match_event_primaryPlayerId_idx_08185961',
        columns: ['primaryPlayerId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'match_event',
        index: 'match_event_relatedPlayerId_idx_89f37bbf',
        columns: ['relatedPlayerId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'match_event',
        index: 'match_event_sequenceId_idx_de377412',
        columns: ['sequenceId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'match_event',
        index: 'match_event_teamId_idx_f2b72ab3',
        columns: ['teamId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'match_statistic',
        index: 'match_statistic_dataSourceId_idx_536a4d74',
        columns: ['dataSourceId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'match_statistic',
        index: 'match_statistic_matchId_idx_4caf5ecc',
        columns: ['matchId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'match_statistic',
        index: 'match_statistic_teamId_idx_f2b72ab3',
        columns: ['teamId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'media_item',
        index: 'media_item_dataSourceId_idx_536a4d74',
        columns: ['dataSourceId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'media_item',
        index: 'media_item_matchId_idx_4caf5ecc',
        columns: ['matchId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'media_item',
        index: 'media_item_playerId_idx_710cf1aa',
        columns: ['playerId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'media_item',
        index: 'media_item_seasonId_idx_aa50cbae',
        columns: ['seasonId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'player',
        index: 'player_displayName_idx_6daae81f',
        columns: ['displayName'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'player',
        index: 'player_isActive_idx_77fe3ba1',
        columns: ['isActive'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'player_absence',
        index: 'player_absence_dataSourceId_idx_536a4d74',
        columns: ['dataSourceId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'player_absence',
        index: 'player_absence_playerId_idx_710cf1aa',
        columns: ['playerId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'player_absence',
        index: 'player_absence_seasonId_idx_aa50cbae',
        columns: ['seasonId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'player_absence',
        index: 'player_absence_status_idx_e98638ab',
        columns: ['status'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'player_match_statistic',
        index: 'player_match_statistic_dataSourceId_idx_536a4d74',
        columns: ['dataSourceId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'player_match_statistic',
        index: 'player_match_statistic_matchId_idx_4caf5ecc',
        columns: ['matchId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'player_match_statistic',
        index: 'player_match_statistic_playerId_idx_710cf1aa',
        columns: ['playerId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'player_match_statistic',
        index: 'player_match_statistic_teamId_idx_f2b72ab3',
        columns: ['teamId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'prediction',
        index: 'prediction_matchId_generatedAt_idx_09dfffce',
        columns: ['matchId', 'generatedAt'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'prediction',
        index: 'prediction_matchId_idx_4caf5ecc',
        columns: ['matchId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'prediction',
        index: 'prediction_modelVersionId_idx_d3fe73a2',
        columns: ['modelVersionId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'provider_mapping',
        index: 'provider_mapping_dataSourceId_idx_536a4d74',
        columns: ['dataSourceId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'provider_mapping',
        index: 'provider_mapping_internalId_idx_1e636b89',
        columns: ['internalId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'season',
        index: 'season_isCurrent_idx_ad7fadcb',
        columns: ['isCurrent'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'season',
        index: 'season_startYear_idx_82265c53',
        columns: ['startYear'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'season_moment',
        index: 'season_moment_dataSourceId_idx_536a4d74',
        columns: ['dataSourceId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'season_moment',
        index: 'season_moment_matchId_idx_4caf5ecc',
        columns: ['matchId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'season_moment',
        index: 'season_moment_playerId_idx_710cf1aa',
        columns: ['playerId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'season_moment',
        index: 'season_moment_seasonId_idx_aa50cbae',
        columns: ['seasonId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'season_moment',
        index: 'season_moment_seasonId_occurredAt_idx_e1c5f3af',
        columns: ['seasonId', 'occurredAt'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'squad_membership',
        index: 'squad_membership_playerId_idx_710cf1aa',
        columns: ['playerId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'squad_membership',
        index: 'squad_membership_seasonId_idx_aa50cbae',
        columns: ['seasonId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'squad_membership',
        index: 'squad_membership_seasonId_teamId_idx_3ad84779',
        columns: ['seasonId', 'teamId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'squad_membership',
        index: 'squad_membership_teamId_idx_f2b72ab3',
        columns: ['teamId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'standing_snapshot',
        index: 'standing_snapshot_competitionId_idx_53fccd3b',
        columns: ['competitionId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'standing_snapshot',
        index: 'standing_snapshot_seasonId_competitionId_matchday_idx_ace98fce',
        columns: ['seasonId', 'competitionId', 'matchday'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'standing_snapshot',
        index: 'standing_snapshot_seasonId_idx_aa50cbae',
        columns: ['seasonId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'standing_snapshot',
        index: 'standing_snapshot_teamId_idx_f2b72ab3',
        columns: ['teamId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'team',
        index: 'team_isBarcelona_idx_01b2b7ad',
        columns: ['isBarcelona'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'trophy_win',
        index: 'trophy_win_competitionId_idx_53fccd3b',
        columns: ['competitionId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'trophy_win',
        index: 'trophy_win_seasonId_idx_aa50cbae',
        columns: ['seasonId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'trophy_win',
        index: 'trophy_win_trophyId_idx_d1689a3f',
        columns: ['trophyId'],
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'favourite_player',
        foreignKey: {
          name: 'favourite_player_playerId_fkey',
          columns: ['playerId'],
          references: { schema: 'public', table: 'player', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'football_match',
        foreignKey: {
          name: 'football_match_seasonId_fkey',
          columns: ['seasonId'],
          references: { schema: 'public', table: 'season', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'football_match',
        foreignKey: {
          name: 'football_match_competitionId_fkey',
          columns: ['competitionId'],
          references: { schema: 'public', table: 'competition', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'football_match',
        foreignKey: {
          name: 'football_match_homeTeamId_fkey',
          columns: ['homeTeamId'],
          references: { schema: 'public', table: 'team', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'football_match',
        foreignKey: {
          name: 'football_match_awayTeamId_fkey',
          columns: ['awayTeamId'],
          references: { schema: 'public', table: 'team', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'kit_theme',
        foreignKey: {
          name: 'kit_theme_seasonId_fkey',
          columns: ['seasonId'],
          references: { schema: 'public', table: 'season', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'lineup',
        foreignKey: {
          name: 'lineup_matchId_fkey',
          columns: ['matchId'],
          references: { schema: 'public', table: 'football_match', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'lineup',
        foreignKey: {
          name: 'lineup_teamId_fkey',
          columns: ['teamId'],
          references: { schema: 'public', table: 'team', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'lineup_player',
        foreignKey: {
          name: 'lineup_player_lineupId_fkey',
          columns: ['lineupId'],
          references: { schema: 'public', table: 'lineup', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'lineup_player',
        foreignKey: {
          name: 'lineup_player_playerId_fkey',
          columns: ['playerId'],
          references: { schema: 'public', table: 'player', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'match_diary_entry',
        foreignKey: {
          name: 'match_diary_entry_matchId_fkey',
          columns: ['matchId'],
          references: { schema: 'public', table: 'football_match', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'match_diary_entry',
        foreignKey: {
          name: 'match_diary_entry_favouritePlayerId_fkey',
          columns: ['favouritePlayerId'],
          references: { schema: 'public', table: 'player', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'match_diary_entry',
        foreignKey: {
          name: 'match_diary_entry_favouriteGoalEventId_fkey',
          columns: ['favouriteGoalEventId'],
          references: { schema: 'public', table: 'match_event', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'match_event',
        foreignKey: {
          name: 'match_event_matchId_fkey',
          columns: ['matchId'],
          references: { schema: 'public', table: 'football_match', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'match_event',
        foreignKey: {
          name: 'match_event_teamId_fkey',
          columns: ['teamId'],
          references: { schema: 'public', table: 'team', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'match_event',
        foreignKey: {
          name: 'match_event_primaryPlayerId_fkey',
          columns: ['primaryPlayerId'],
          references: { schema: 'public', table: 'player', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'match_event',
        foreignKey: {
          name: 'match_event_relatedPlayerId_fkey',
          columns: ['relatedPlayerId'],
          references: { schema: 'public', table: 'player', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'match_event',
        foreignKey: {
          name: 'match_event_dataSourceId_fkey',
          columns: ['dataSourceId'],
          references: { schema: 'public', table: 'data_source', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'match_statistic',
        foreignKey: {
          name: 'match_statistic_matchId_fkey',
          columns: ['matchId'],
          references: { schema: 'public', table: 'football_match', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'match_statistic',
        foreignKey: {
          name: 'match_statistic_teamId_fkey',
          columns: ['teamId'],
          references: { schema: 'public', table: 'team', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'match_statistic',
        foreignKey: {
          name: 'match_statistic_dataSourceId_fkey',
          columns: ['dataSourceId'],
          references: { schema: 'public', table: 'data_source', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'media_item',
        foreignKey: {
          name: 'media_item_seasonId_fkey',
          columns: ['seasonId'],
          references: { schema: 'public', table: 'season', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'media_item',
        foreignKey: {
          name: 'media_item_matchId_fkey',
          columns: ['matchId'],
          references: { schema: 'public', table: 'football_match', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'media_item',
        foreignKey: {
          name: 'media_item_playerId_fkey',
          columns: ['playerId'],
          references: { schema: 'public', table: 'player', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'media_item',
        foreignKey: {
          name: 'media_item_dataSourceId_fkey',
          columns: ['dataSourceId'],
          references: { schema: 'public', table: 'data_source', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'player_absence',
        foreignKey: {
          name: 'player_absence_seasonId_fkey',
          columns: ['seasonId'],
          references: { schema: 'public', table: 'season', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'player_absence',
        foreignKey: {
          name: 'player_absence_playerId_fkey',
          columns: ['playerId'],
          references: { schema: 'public', table: 'player', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'player_absence',
        foreignKey: {
          name: 'player_absence_dataSourceId_fkey',
          columns: ['dataSourceId'],
          references: { schema: 'public', table: 'data_source', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'player_match_statistic',
        foreignKey: {
          name: 'player_match_statistic_matchId_fkey',
          columns: ['matchId'],
          references: { schema: 'public', table: 'football_match', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'player_match_statistic',
        foreignKey: {
          name: 'player_match_statistic_playerId_fkey',
          columns: ['playerId'],
          references: { schema: 'public', table: 'player', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'player_match_statistic',
        foreignKey: {
          name: 'player_match_statistic_teamId_fkey',
          columns: ['teamId'],
          references: { schema: 'public', table: 'team', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'player_match_statistic',
        foreignKey: {
          name: 'player_match_statistic_dataSourceId_fkey',
          columns: ['dataSourceId'],
          references: { schema: 'public', table: 'data_source', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'prediction',
        foreignKey: {
          name: 'prediction_matchId_fkey',
          columns: ['matchId'],
          references: { schema: 'public', table: 'football_match', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'prediction',
        foreignKey: {
          name: 'prediction_modelVersionId_fkey',
          columns: ['modelVersionId'],
          references: { schema: 'public', table: 'model_version', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'provider_mapping',
        foreignKey: {
          name: 'provider_mapping_dataSourceId_fkey',
          columns: ['dataSourceId'],
          references: { schema: 'public', table: 'data_source', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'season_moment',
        foreignKey: {
          name: 'season_moment_seasonId_fkey',
          columns: ['seasonId'],
          references: { schema: 'public', table: 'season', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'season_moment',
        foreignKey: {
          name: 'season_moment_matchId_fkey',
          columns: ['matchId'],
          references: { schema: 'public', table: 'football_match', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'season_moment',
        foreignKey: {
          name: 'season_moment_playerId_fkey',
          columns: ['playerId'],
          references: { schema: 'public', table: 'player', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'season_moment',
        foreignKey: {
          name: 'season_moment_dataSourceId_fkey',
          columns: ['dataSourceId'],
          references: { schema: 'public', table: 'data_source', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'squad_membership',
        foreignKey: {
          name: 'squad_membership_seasonId_fkey',
          columns: ['seasonId'],
          references: { schema: 'public', table: 'season', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'squad_membership',
        foreignKey: {
          name: 'squad_membership_teamId_fkey',
          columns: ['teamId'],
          references: { schema: 'public', table: 'team', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'squad_membership',
        foreignKey: {
          name: 'squad_membership_playerId_fkey',
          columns: ['playerId'],
          references: { schema: 'public', table: 'player', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'standing_snapshot',
        foreignKey: {
          name: 'standing_snapshot_seasonId_fkey',
          columns: ['seasonId'],
          references: { schema: 'public', table: 'season', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'standing_snapshot',
        foreignKey: {
          name: 'standing_snapshot_competitionId_fkey',
          columns: ['competitionId'],
          references: { schema: 'public', table: 'competition', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'standing_snapshot',
        foreignKey: {
          name: 'standing_snapshot_teamId_fkey',
          columns: ['teamId'],
          references: { schema: 'public', table: 'team', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'trophy_win',
        foreignKey: {
          name: 'trophy_win_trophyId_fkey',
          columns: ['trophyId'],
          references: { schema: 'public', table: 'trophy', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'trophy_win',
        foreignKey: {
          name: 'trophy_win_seasonId_fkey',
          columns: ['seasonId'],
          references: { schema: 'public', table: 'season', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'trophy_win',
        foreignKey: {
          name: 'trophy_win_competitionId_fkey',
          columns: ['competitionId'],
          references: { schema: 'public', table: 'competition', columns: ['id'] },
        },
      }),
    ];
  }
}

MigrationCLI.run(import.meta.url, M);
