import type { SourceProfile } from "./types";

export const SOURCE_PROFILES = {
  footballData: {
    id: "football-data-org",
    name: "football-data.org",
    classification: "OFFICIAL_API",
    automationPolicy: "ALLOW",
    accessMode: "documented REST API",
    currentSeasonExpected: true,
    requiresCredential: true,
    documentationUrl: "https://docs.football-data.org/general/v4/",
    termsUrl: "https://www.football-data.org/terms",
    summary: "Stable documented API; the free tier covers La Liga basics.",
    limitations: [
      "Free tier is limited to 10 requests per minute.",
      "Detailed lineups, goals, substitutions, and cards require the Deep Data add-on.",
      "Attribution is required and the API token must remain server-side.",
    ],
  },
  theSportsDb: {
    id: "thesportsdb",
    name: "TheSportsDB",
    classification: "OFFICIAL_API",
    automationPolicy: "ALLOW",
    accessMode: "documented REST API",
    currentSeasonExpected: true,
    requiresCredential: false,
    documentationUrl: "https://www.thesportsdb.com/documentation",
    termsUrl: "https://www.thesportsdb.com/docs_terms_of_use.php",
    summary: "Legal development API with a public free key and broad event endpoints.",
    limitations: [
      "The free API returns at most five lineup, timeline, and statistics rows per endpoint.",
      "Data is community maintained and should be treated as secondary enrichment.",
      "TheSportsDB requires source credit; app-store publication requires a paid subscription.",
    ],
  },
  statsBomb: {
    id: "statsbomb-open-data",
    name: "StatsBomb Open Data",
    classification: "OFFICIAL_API",
    automationPolicy: "ALLOW",
    accessMode: "official open GitHub dataset",
    currentSeasonExpected: false,
    requiresCredential: false,
    documentationUrl: "https://github.com/statsbomb/open-data",
    termsUrl: "https://github.com/statsbomb/open-data/blob/master/LICENSE.pdf",
    summary: "Rich, legitimate event data for research, but not a current-season feed.",
    limitations: [
      "The published La Liga catalogue currently ends at 2020/21.",
      "StatsBomb attribution and logo requirements apply.",
      "This is an open dataset, not a live API; OFFICIAL_API is the closest requested classification.",
    ],
  },
  openFootball: {
    id: "openfootball",
    name: "openfootball / football.json",
    classification: "PUBLIC_API_UNDOCUMENTED",
    automationPolicy: "ALLOW",
    accessMode: "documented CC0 static JSON on GitHub",
    currentSeasonExpected: true,
    requiresCredential: false,
    documentationUrl: "https://github.com/openfootball/football.json",
    termsUrl: "https://github.com/openfootball/football.json/blob/master/LICENSE.md",
    summary: "CC0 fixture/result mirror generated daily from community Football.TXT data.",
    limitations: [
      "Community-maintained data is not an official league feed.",
      "Only fixture/result fields are useful for this lab; there are no rich match details.",
      "PUBLIC_API_UNDOCUMENTED is the closest requested class; this is actually a documented static dataset, not an API.",
    ],
  },
  statsHawk: {
    id: "statshawk",
    name: "StatsHawk",
    classification: "OFFICIAL_API",
    automationPolicy: "ALLOW",
    accessMode: "documented REST API",
    currentSeasonExpected: true,
    requiresCredential: true,
    documentationUrl: "https://www.statshawk.ai/docs",
    termsUrl: "https://www.statshawk.ai/terms",
    summary: "New documented API with La Liga, a 5,000-unit free tier, and explicit app caching rights.",
    limitations: [
      "Verified against the current La Liga schedule, contest detail, box score, roster, capabilities, and one player overview.",
      "Its roster is not a confirmed match lineup; no formation, bench role, match position, or shirt number should be inferred from it.",
      "Soccer injury history is not currently covered by the documented injury surface.",
      "Soccer refreshes hourly and is not presented as a licensed enterprise feed.",
      "Free keys are test keys; production requirements should be confirmed before adoption.",
    ],
  },
  understat: {
    id: "understat",
    name: "Understat",
    classification: "RESTRICTED_DO_NOT_AUTOMATE",
    automationPolicy: "DENY",
    accessMode: "public website, manual review only",
    currentSeasonExpected: true,
    requiresCredential: false,
    documentationUrl: "https://understat.com/",
    termsUrl: "https://understat.com/robots.txt",
    summary: "The site exposes useful xG pages, but its robots policy disallows all automated access.",
    limitations: [
      "robots.txt currently contains Disallow: / for all user agents.",
      "No official public API or clear automation licence was found.",
    ],
  },
  fotmob: {
    id: "fotmob",
    name: "FotMob",
    classification: "RESTRICTED_DO_NOT_AUTOMATE",
    automationPolicy: "DENY",
    accessMode: "public website, manual review only",
    currentSeasonExpected: true,
    requiresCredential: false,
    documentationUrl: "https://www.fotmob.com/",
    termsUrl: "https://www.fotmob.com/tos.txt",
    summary: "Rich consumer match pages, but automated or systematic access is prohibited.",
    limitations: ["No public developer API was found.", "Do not use reverse-engineered endpoints."],
  },
  sofaScore: {
    id: "sofascore",
    name: "SofaScore",
    classification: "RESTRICTED_DO_NOT_AUTOMATE",
    automationPolicy: "DENY",
    accessMode: "public website, manual review only",
    currentSeasonExpected: true,
    requiresCredential: false,
    documentationUrl: "https://www.sofascore.com/",
    termsUrl: "https://www.sofascore.com/terms-and-conditions",
    summary: "Rich consumer data, but the terms prohibit scraping, extraction, and aggregation without consent.",
    limitations: ["No public developer API was found.", "Do not use reverse-engineered endpoints."],
  },
  espn: {
    id: "espn",
    name: "ESPN",
    classification: "RESTRICTED_DO_NOT_AUTOMATE",
    automationPolicy: "DENY",
    accessMode: "public website, manual review only",
    currentSeasonExpected: true,
    requiresCredential: false,
    documentationUrl: "https://www.espn.com/soccer/",
    termsUrl: "https://www.disneyplus.com/welcome/subscriber-agreement",
    summary: "Current keyless JSON endpoints are undocumented and Disney/ESPN terms prohibit automated extraction.",
    limitations: ["The former public ESPN developer API is not a current supported product.", "Do not use undocumented endpoints."],
  },
  laLiga: {
    id: "laliga-official",
    name: "LaLiga official",
    classification: "RESTRICTED_DO_NOT_AUTOMATE",
    automationPolicy: "DENY",
    accessMode: "official public web/app, manual review only",
    currentSeasonExpected: true,
    requiresCredential: false,
    documentationUrl: "https://www.laliga.com/",
    termsUrl: "https://www.laliga.com/en-GB/legal/legal-oficial",
    summary: "Authoritative presentation source, but no public developer API or automation permission was found.",
    limitations: ["App access is framed as personal/private use.", "Do not automate without written permission."],
  },
  uefa: {
    id: "uefa-official",
    name: "UEFA official",
    classification: "RESTRICTED_DO_NOT_AUTOMATE",
    automationPolicy: "DENY",
    accessMode: "official public website, manual review only",
    currentSeasonExpected: true,
    requiresCredential: false,
    documentationUrl: "https://www.uefa.com/",
    termsUrl: "https://www.uefa.com/news-media/news/0256-0dc91ad71f32-ce04913814f0-1000--general-terms-and-conditions/",
    summary: "Authoritative competition source whose terms prohibit systematic automated collection.",
    limitations: ["No suitable free public developer API was found.", "UEFA reserves competition data and statistics rights."],
  },
  pitchApi: {
    id: "pitchapi",
    name: "PitchAPI",
    classification: "UNKNOWN_DO_NOT_AUTOMATE",
    automationPolicy: "DENY",
    accessMode: "documented REST API, legal provenance not yet verified",
    currentSeasonExpected: true,
    requiresCredential: true,
    documentationUrl: "https://pitchapi.dev/",
    termsUrl: null,
    summary: "Promising free rich-data API, but no public terms or upstream licensing statement was found.",
    limitations: ["Do not integrate until ownership, data provenance, and reuse terms are confirmed in writing."],
  },
  footballDataUk: {
    id: "football-data-uk",
    name: "football-data.co.uk",
    classification: "RESTRICTED_DO_NOT_AUTOMATE",
    automationPolicy: "DENY",
    accessMode: "downloadable CSV, private manual use only",
    currentSeasonExpected: true,
    requiresCredential: false,
    documentationUrl: "https://www.football-data.co.uk/data.php",
    termsUrl: "https://www.football-data.co.uk/data.php",
    summary: "Useful current CSVs, but the owner explicitly excludes automated bots, AI, commercial use, and data-training products.",
    limitations: ["Not suitable for this automated dashboard lab without explicit permission."],
  },
  apiFootball: {
    id: "api-football",
    name: "API-Football",
    classification: "OFFICIAL_API",
    automationPolicy: "ALLOW",
    accessMode: "documented REST API",
    currentSeasonExpected: false,
    requiresCredential: true,
    documentationUrl: "https://www.api-football.com/documentation-v3",
    termsUrl: "https://www.api-football.com/terms",
    summary: "Legitimate API, but the free plan does not cover the current La Liga season for this project.",
    limitations: ["Keep only as a historical development benchmark; do not design current coverage around it."],
  },
} as const satisfies Record<string, SourceProfile>;

export const ALL_SOURCE_PROFILES: SourceProfile[] = Object.values(SOURCE_PROFILES);
